spring:
  datasource:
    url: jdbc:mysql://localhost:3306/text_to_sql?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
      physical_naming_strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        jdbc:
          batch_size: 30
          order_inserts: true
          order_updates: true

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=100,expireAfterWrite=1h

  security:
    user:
      name: admin
      password: admin123
      roles: USER

ollama:
  model:
    name: llama3.2
    baseurl: http://localhost:11434
